import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme,
      colors,
        popover,
        primary,
        secondary,
        muted,
        accent,
        destructive,
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart,
        sidebar,
      },
      keyframes,
          to,
        },
        "accordion-up",
          to,
        },
      },
      animation,
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
